# Training Config
## Training device
device: "cuda:7"
## Environment name / maximum episode length
env: pendulum
max_episode_len: 1000
## Data collection and optimization loop
seed: 0
num_envs: 1
num_steps: 2048
num_mini_batch: 32
ppo_epoch: 10
max_training_steps: 1000000
## Handling of timesteps
discount_factor: 0.99
## Optimizer
lr: 0.0003
use_linear_lr_decay: true
# Model structure config
model_type: PPO
hidden_dim: &hidden_dim 64
use_recurrent: false
# PPO config
clip_param: 0.20
value_loss_coef: 0.5
entropy_coef: 0
max_grad_norm: 0.5
use_clipped_value_loss: true
use_gae: true
gae_lambda: 0.95
use_proper_time_limits: true

# Test
eval_freq: 50
test_num_episodes: 10
test_max_episode_len: 1000
test_gui: true
# model_path: /data2/cwkang/RL/git/repro/rep2/results/22-06-28/21-07-18/checkpoint_450.tar

# Logging / Saving
log_freq: 1
save_freq: 50

# Domain randomization [domain_name, lower_bound, upper_bound, step_size] (lower, upper bounds are multipliers)
# domain_randomization:
#   - [m, 0.5, 1.51, 0.25]
#   - [l, 0.5, 1.51, 0.25]

# --- Model Structure ----
act: &act Tanh
actor_net: &actor_net
  - [Linear, auto, *hidden_dim, {}]
  - *act
  - [Linear, *hidden_dim, *hidden_dim, {}]
  - *act
  - [Linear, *hidden_dim, auto, {}]
critic_net: &critic_net
  - [Linear, auto, *hidden_dim, {}]
  - *act
  - [Linear, *hidden_dim, *hidden_dim, {}]
  - *act
  - [Linear, *hidden_dim, auto, {}]

# --- Models ---
actor: *actor_net
critic: *critic_net